language: android
jdk:
- oraclejdk8
env:
  global:
  - secure: H/KTyfddpCfKZgG52Qbd45yTR8AJ5lU9sO7MOHz/eJaXfWFoEy+UrHY7yzmcsNw5GafQ4tagLyPzL2ynESH1synxaTMR3n+LsqQqgHFN31pbhjIvpqv+BaS8cGcyNf3G0UCiZsfQAxFCsEE+QI/STW4bEj/9oEZ3c93/5tQPOJtTs0C6qXDfaZk7PlaZ2UatC96a2CX+HGE59ovbCjTFX6pi7BNbjQyWRLrj2kzB+qY17ayQx/1LAUxDbtsQrrx0qkaTyDPVlw2fCg47JTm5vWEGu4cY0ZqH8EVXOidCeb8L76q6mGDI+C6QIk9yfXWulio1uoC3794e41hZZTQn9Wj3dVdd76R6F6TsMhwMlBUd2KP0v0cDLQk3pKIeGucV+AcecciWM+gBGAU5ZLJUKugYgy3Zehz+qVM19OTQQYsxK5kWlvREwYYiF/XHf7wzJg67iS3NDXSjL+GTekIGDn95Cm2IYILksQE1RDw6k5eNkTHZWdp+AR632pH59euZhZoCOnky9YFH88ZAqMHTxYdvCaDAsSYegb1Vwb4rh8fIddZyDhPFcu8CVQlk/RutqsOTr38kbo2gf33QbNMzxoF2enaFjR42JDe6RxJ42CMFs9X9EouMZ/IKjnAWxBxNTCFCzZDHEg4z7LE8gUxxxUnYLU6boYWUnJO7UbGod+k=
  - secure: eMHTAHGyGAN8HZgKbQ6cGtv4hmkq1GRUIU4tBxNwayrvq2OCm3JBKrkIh50ZMt8w2rzVjBOf8gHZRXFczzUn8dqngDaICljl/Xq/eeIshyaoPn/QQ7qjCZfPXyiv0SxtOaDj6zq2A39XRfF0AAxIOxhZZoiunekjZfpDoGlvrWugaUm9foKRQyYG6bPOF+6bIcAecq4bRz3zx+wGMW3/jMdZVys+NP95wJV3KJ4TvpFXfkbQjzNf+s6KuP/z9OglukRhyKtFdMit/Ixuu2TxpBWhH9dZFXgLHCKbfR6/yUKr9eITIz3qkiXSyDlvF6JRLiHtsfoJAnRblhej6t463GObWWTE+49wFJ6qIbjWsiqZzpEWp9oAZYDQxIrLsSfq4EzXMNyw++GLllqp9nEaZGGugQLoCynu/0LqzGiqctmuBpIFvIdTE6o9qZyaEaDLvoZd832PIHrbM2i6tY/3onCDavD+yxi05ktO5nbx1rNNytGcxZ9F4mZM/sjiU83dhApjBpGkdQgJ2VmFCFvgDikO2vlyeMUNV/yYiXuQqieGgQS5ZGy2fHVckmjd8g7bkvCCL0Z/ngKAhP17QRoaDTK1pk0bD7dNIiOkcx4qUAoC1A2WWUrPgZ4xNjnq9I30I4pxTjjkM2UphUPk82XJa1yS0yOC1TO69l5fPyMOtYs=
android:
  components:
  - tools
  - platform-tools
  - tools
  - android-28
licenses:
- android-sdk-preview-license-52d11cd2
- android-sdk-license-.+
- google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
notifications:
  email: false
before_script:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script: "./gradlew assembleRelease"
deploy:
  provider: script
  script: echo $BINTRAY_USER && ./gradlew core:clean && ./gradlew core:build && ./gradlew
    core:install && ./gradlew core:bintrayUpload
  skip_cleanup: true
  dry_run: true
  on:
    tags: true
