jobs:
  include:
    - stage: test
      script: echo "Ahoj"
    - # stage name not required, will continue to use `test`
      script: script: echo "Ahoj 2"
    - stage: deploy
      script: echo "Ahoj 3"
