language: android
jdk:
- oraclejdk8
env:
  global:
  - secure: "mCg8XRqidvso0PLj+WkzNC1Y4QDf+ezJaAzJ0xfz/JF1rAMiDnCeYWf6oAJDu3+XfCuVSsQmp5pM+eJVEzBHd7LmBeJQsoYLqwb04ztNTdxtDc/ycOKv26snnniW+oRu4xBdZguPryYlcEoReleYUYgL2I3ME+OLdSs5hozTrrDPPwfzOp6wnThnv4OPdxdjvI8nVHi0rXYE9SrULaErXu9py+f/gCo3hc526XoW21Q+miN6HRzsKf5S93PGD/L6G8BFmHRXpDEqcKZVhAw+5gEk+glJ9aS1f8LoMSWGaBEbt/GYKgL9dQ/HxZexWGY1ECshudySvV9AnqiS33QSkJDUGOk4V4GGd/WBPAE0STlEhWPJK9kzyTNV/ZzzEVGwI+GEt0E31c364P7W7DPOzRjjCF9rT0YYooxXjqVb/8o9YrxFnTu5m2ZK2Id/5ZggFYWRlalmitWyjIBXvEQF8RsztT3LQeeFawuuZSPtmSjfqnbuDZDfY3aKjyl6uUmV+uQi/ZrEkVCS7NdPCA80Kt5A1fltg4VV0eEIupIw3Oe4skEWcqHHh/cCaCeBSspQ78hozb1AsHAIUj0XtjXsQ0wNiTIAeN7w2L67X0qQHbaV7/HDBtNKYBPMzUfEltfcfWyliIHEj4IwjZx1CmfMBpoztQf89g+levW6WpFSQg4="
  - secure: "LNZPyRW12r4a1F9CAydv/D2j+eZu6PW7HL//QfEX0fw/zjk7Zen+s6195XIuCjEjZF5eXakVKj1kuhlsfVdk+h8MvrWvG1xgwVZ4jjBEpJ0vb0B0+WGcX8arhOWiED/zhsmGTYMTPe4BmGuyQgx24fhNFzJhw6PvIDC44LyF13VfySY6m4RWn56Z5nVX8VI+uscAp50sgbpHqi9oW4kpMhZi27Va6ZGDDa/OSnqhPpEal8O7+AAuHs9Ys56ygK9go4OE+pkOd542wLrsB0QXKSwdocZV51mJZMmie1jbnM4rZbP0dcygR44xig7r79RuBb8o+QfLS+i262BVGByCTut+lKuku9YOy+YehUH/JqJcG5GtbEHZHhrNobaZmbJejkGafalV4TE09zIIclXbrp+MXy3lepWGurR+p4HPGViWrB3J7kOMzMoiFkGsSdxYVZoY4Y9+mL6r/I8cfBGdjdngLX3yqpDBO76i0/V+8wsWqejFYbMwHXD4ycaGISZJPjbUHhbQlOky7DcbGRKpdZ81/1GOGA9LPK2bZS5kYtDg6RSYTyAisTXDVMTyIRsdmLt/HdYUJkl+Prv0eaDmHbUlhOXVcMs5XdMH2bqrKpouK4pv687d1S7F1rwirQbIrqG7rzU+DiX1aF4ZAJXZS41jPOVDR6YQzkn2xxOIDeo="
android:
  components:
  - tools
  - platform-tools
  - tools
  - android-28
licenses:
- android-sdk-preview-license-52d11cd2
- android-sdk-license-.+
- google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
notifications:
  email: false
before_script:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script: "./gradlew assembleRelease"
deploy:
  provider: script
  script: echo $BINTRAY_USER && ./gradlew core:clean && ./gradlew core:build && ./gradlew
    core:install && ./gradlew core:bintrayUpload
  skip_cleanup: true
  dry_run: true
  on:
    tags: true
